yaml_path: /data/home/zhoupc/github/ease_project/pinky40_config.yaml
data_folder: /data/home/zhoupc/github/ease_project/data/pinky40
output_folder: /data/home/zhoupc/github/ease_project/results/pinky40
denoised_folder: cropped_denoised_video
raw_folder: cropped_raw_video
matfile_video: functional_data.mat
matfile_stack: stack_2p.mat
registration_csv: registration.csv
matfile_transformation: coor_convert.mat
matfile_em: em_1.mat
video_shifts:
  ii:
  - [0.0, 0.0, -1.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -6.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -5.0]
  - [-3.0, -4.0, -4.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -3.0, -4.0]
  jj:
  - [2.0, 2.0, 2.0]
  - [0.0, 0.0, -1.0]
  - [0.0, -1.0, 0.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
  - [-3.0, -3.0, -3.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
video_zvals:
- [168.0, 159.0, 153.0]
- [147.0, 139.0, 133.0]
- [122.0, 112.0, 107.0]
- [99.0, 91.0, 85.0]
- [73.0, 67.0, 58.0]
- [58.0, 50.0, 45.0]
- [39.0, 29.0, 23.0]
- [17.0, 6.0, 2.0]
video_zvals_updated:
- [169.0, 160.0, 153.0]
- [147.0, 138.0, 132.0]
- [122.0, 113.0, 107.0]
- [100.0, 90.0, 85.0]
- [78.0, 66.0, 60.0]
- [59.0, 50.0, 45.0]
- [39.0, 29.0, 22.0]
- [17.0, 6.0, 2.0]
video_Fs: 15.0
video_T: 9100.0
use_denoise: false
stack_shifts:
  ii:
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 0.0]
  - [1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  jj:
  - [1.0, 1.0, 1.0]
  - [1.0, 1.0, 0.0]
  - [1.0, 0.0, 1.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [-1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -1.0]
d1: 58.0
d2: 129.0
d3: 3.0
extra_margin: 5.0
FOV: [113.0, 170.0, 39.0, 167.0]
FOV_stack: [225.0, 340.0, 77.0, 334.0]
align_max_zshift: 1.0
num_scans: 8.0
num_slices: 3.0
num_blocks: 3.0
dims_stack: [512.0, 512.0, 310.0]
dims_video: [256.0, 256.0]
range_2p: [400.0, 400.0, 310.0]
scan_id: 1.0
slice_id: 1.0
block_id: 0.0
options_init: {init_method: tf, order_statistics: l3norm, min_similarity: 0.6, clear_results: false,
  save_fig: false, K_candidate: 3000.0, show_fig: true, K_new: 50.0}
show_em_only: false
em_shifts:
  ii:
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -3.0]
  - [-2.0, -3.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -3.0, -3.0]
  jj:
  - [-2.0, -2.0, -2.0]
  - [-2.0, -2.0, -3.0]
  - [-2.0, -3.0, -2.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -2.0, -3.0]
  - [-4.0, -3.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -3.0, -4.0]
em_segmentation: 1.0
em_load_flag: true
em_zblur: 8.0
em_scale_factor: 8.950000000000001E-4
score_method: corr
nam_show: cn
